// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import ()

type CartItem struct {
	ShoppingcartID int32
	ProductID      int32
	UserID         int32
	Quantity       int32
}
