apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingcart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingcart
  template:
    metadata:
      labels:
        app: shoppingcart
    spec:
      containers:
      - name: shoppingcart
        image: your-image-name-here
        ports:
        - containerPort: 50052
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_HOST
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingcart
spec:
  selector:
    app: shoppingcart
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
