apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanagement
  template:
    metadata:
      labels:
        app: usermanagement
    spec:
      containers:
      - name: usermanagement
        image: your-image-name-here
        ports:
        - containerPort: 50050
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_HOST
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: usermanagement
spec:
  selector:
    app: usermanagement
  ports:
    - protocol: TCP
      port: 50050
      targetPort: 50050
