// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import ()

type Order struct {
	OrderID    int32
	UserID     int32
	TotalPrice int32
	Status     string
}

type OrderItem struct {
	OrderItemsID int32
	OrderID      int32
	ProductID    int32
	Quantity     int32
}

type Payment struct {
	PaymentID     int32
	OrderID       int32
	PaymentMethod string
}
