// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import ()

type Product struct {
	ProductID   int32
	UserID      int32
	Name        string
	Url         string
	Title       string
	Description string
	Price       int32
}
