package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"graphql_api/graph/model"
	checkout "graphql_api/protos/checkoutpb"
	"graphql_api/protos/productspb"
	"graphql_api/protos/usermanagementpb"
)

// Role is the resolver for the role field.
func (r *userResolver) Role(ctx context.Context, obj *usermanagementpb.User) (model.Role, error) {
	panic(fmt.Errorf("not implemented: Role - role"))
}

// Products is the resolver for the products field.
func (r *userResolver) Products(ctx context.Context, obj *usermanagementpb.User) ([]*productspb.Product, error) {
	panic(fmt.Errorf("not implemented: Products - products"))
}

// Orders is the resolver for the orders field.
func (r *userResolver) Orders(ctx context.Context, obj *usermanagementpb.User) ([]*checkout.OrderDetails, error) {
	panic(fmt.Errorf("not implemented: Orders - orders"))
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *userResolver) Porducts(ctx context.Context, obj *usermanagementpb.User) ([]*productspb.Product, error) {
	panic(fmt.Errorf("not implemented: Porducts - porducts"))
}
