# Use Node 18 as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and yarn.lock to the container
COPY package.json yarn.lock ./

# Install dependencies using Yarn
RUN yarn install

# Copy the rest of the application code to the container
COPY . .

# Expose port 3000 to make the app accessible
EXPOSE 3000

# Command to run the React app
CMD ["yarn", "start"]
